"use strict";
exports.__esModule = true;
exports.userSessionSchema = void 0;
// Generated by ts-to-zod
var zod_1 = require("zod");
exports.userSessionSchema = zod_1.z.object({
    apiKey: zod_1.z.string()
});
